"""
Generates Figma Plugin API JavaScript scripts for creating FigJam boards.
Each function returns a JS string that can be pasted into the Figma Plugin Dev Console.
"""
import json
from typing import Any


def _js_string(s: str) -> str:
    return json.dumps(str(s))


def _section(title: str, x: int, y: int, w: int, h: int, color: str = "#F5F5F5") -> str:
    return f"""
(function() {{
  const section = figma.createSection();
  section.name = {_js_string(title)};
  section.x = {x}; section.y = {y};
  section.resizeWithoutConstraints({w}, {h});
  figma.currentPage.appendChild(section);
  return section;
}})()"""


def _sticky(text: str, x: int, y: int, color_key: str = "YELLOW") -> str:
    colors = {
        "YELLOW":  "{ r: 1.0, g: 0.95, b: 0.4, a: 1 }",
        "PINK":    "{ r: 1.0, g: 0.7,  b: 0.8, a: 1 }",
        "BLUE":    "{ r: 0.7, g: 0.87, b: 1.0, a: 1 }",
        "GREEN":   "{ r: 0.7, g: 1.0,  b: 0.7, a: 1 }",
        "ORANGE":  "{ r: 1.0, g: 0.8,  b: 0.5, a: 1 }",
        "PURPLE":  "{ r: 0.85,g: 0.75, b: 1.0, a: 1 }",
        "RED":     "{ r: 1.0, g: 0.6,  b: 0.6, a: 1 }",
        "WHITE":   "{ r: 1.0, g: 1.0,  b: 1.0, a: 1 }",
    }
    fill = colors.get(color_key.upper(), colors["YELLOW"])
    return f"""
(function() {{
  const sticky = figma.createSticky();
  sticky.x = {x}; sticky.y = {y};
  await figma.loadFontAsync({{ family: 'Inter', style: 'Regular' }});
  sticky.text.characters = {_js_string(text)};
  sticky.fills = [{{ type: 'SOLID', color: {fill} }}];
  figma.currentPage.appendChild(sticky);
  return sticky;
}})()"""


def _text_node(text: str, x: int, y: int, size: int = 16, bold: bool = False) -> str:
    weight = "Bold" if bold else "Regular"
    return f"""
(function() {{
  await figma.loadFontAsync({{ family: 'Inter', style: '{weight}' }});
  const t = figma.createText();
  t.x = {x}; t.y = {y};
  t.fontName = {{ family: 'Inter', style: '{weight}' }};
  t.fontSize = {size};
  t.characters = {_js_string(text)};
  figma.currentPage.appendChild(t);
  return t;
}})()"""


def _rect(x: int, y: int, w: int, h: int, r: int, g: int, b_: int, name: str = "") -> str:
    return f"""
(function() {{
  const rect = figma.createRectangle();
  rect.x = {x}; rect.y = {y};
  rect.resize({w}, {h});
  rect.fills = [{{ type: 'SOLID', color: {{ r: {r/255:.3f}, g: {g/255:.3f}, b: {b_/255:.3f} }} }}];
  rect.name = {_js_string(name)};
  figma.currentPage.appendChild(rect);
  return rect;
}})()"""


def build_figjam_script(board_type: str, data: dict) -> str:
    """Dispatch to the correct board builder."""
    builders = {
        "proto_persona":    _build_persona_board,
        "research_synthesis": _build_affinity_board,
        "journey_map":      _build_journey_board,
        "design_thinking":  _build_design_thinking_board,
        "ux_laws":          _build_ux_laws_board,
    }
    builder = builders.get(board_type, _build_generic_board)
    body = builder(data)
    return _wrap_in_plugin(board_type, body)


def _wrap_in_plugin(board_type: str, body: str) -> str:
    title = {
        "proto_persona":      "Proto Persona Board",
        "research_synthesis": "Research Synthesis — Affinity Map",
        "journey_map":        "User Journey Map",
        "design_thinking":    "Design Thinking Canvas",
        "ux_laws":            "UX Laws & Principles Reference",
    }.get(board_type, board_type.replace("_", " ").title())

    return f"""// ===================================================
// {title}
// Generated by UX Research Agent
// Paste into: Figma → Plugins → Development → Open Console
// ===================================================

async function run() {{
  figma.currentPage.name = {_js_string(title)};

{body}

  figma.viewport.scrollAndZoomIntoView(figma.currentPage.children);
  figma.notify({_js_string(f"{title} created!")});
  figma.closePlugin();
}}

run().catch(err => {{
  figma.notify('Error: ' + err.message, {{ error: true }});
  figma.closePlugin();
}});"""


def _build_persona_board(data: dict) -> str:
    personas = data.get("personas", [])
    lines = []
    for i, persona in enumerate(personas):
        col_x = i * 700
        name = persona.get("name", f"Persona {i+1}")
        occupation = persona.get("occupation", "")
        age = persona.get("age", "")
        goal = persona.get("primary_goal", "")
        quote = persona.get("quote", "")
        tech = persona.get("tech_comfort", 3)
        frustrations = persona.get("frustrations", [])
        motivations = persona.get("motivations", [])
        traits = persona.get("behavioral_traits", [])
        laws = persona.get("relevant_ux_laws", [])

        lines.append(f"""
  // ─── Persona {i+1}: {name} ───
  const frame{i} = figma.createFrame();
  frame{i}.name = {_js_string(name)};
  frame{i}.x = {col_x}; frame{i}.y = 0;
  frame{i}.resize(640, 900);
  frame{i}.fills = [{{ type: 'SOLID', color: {{ r: 0.98, g: 0.98, b: 0.98 }} }}];
  frame{i}.cornerRadius = 12;
  figma.currentPage.appendChild(frame{i});

  // Header
  const hdr{i} = figma.createRectangle();
  hdr{i}.resize(640, 120); hdr{i}.x = 0; hdr{i}.y = 0;
  hdr{i}.fills = [{{ type: 'SOLID', color: {{ r: 0.12, g: 0.12, b: 0.12 }} }}];
  hdr{i}.cornerRadius = 12;
  frame{i}.appendChild(hdr{i});

  await figma.loadFontAsync({{ family: 'Inter', style: 'Bold' }});
  await figma.loadFontAsync({{ family: 'Inter', style: 'Regular' }});
  await figma.loadFontAsync({{ family: 'Inter', style: 'Medium' }});

  const nameText{i} = figma.createText();
  nameText{i}.fontName = {{ family: 'Inter', style: 'Bold' }};
  nameText{i}.fontSize = 24; nameText{i}.x = 24; nameText{i}.y = 20;
  nameText{i}.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 1, b: 1 }} }}];
  nameText{i}.characters = {_js_string(name)};
  frame{i}.appendChild(nameText{i});

  const subText{i} = figma.createText();
  subText{i}.fontName = {{ family: 'Inter', style: 'Regular' }};
  subText{i}.fontSize = 14; subText{i}.x = 24; subText{i}.y = 52;
  subText{i}.fills = [{{ type: 'SOLID', color: {{ r: 0.7, g: 0.7, b: 0.7 }} }}];
  subText{i}.characters = {_js_string(f"{occupation} · Age {age} · Tech {tech}/5")};
  frame{i}.appendChild(subText{i});

  // Quote
  const quoteBox{i} = figma.createRectangle();
  quoteBox{i}.resize(592, 68); quoteBox{i}.x = 24; quoteBox{i}.y = 136;
  quoteBox{i}.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 0.97, b: 0.8 }} }}];
  quoteBox{i}.cornerRadius = 8;
  frame{i}.appendChild(quoteBox{i});

  const quoteText{i} = figma.createText();
  quoteText{i}.fontName = {{ family: 'Inter', style: 'Regular' }};
  quoteText{i}.fontSize = 13; quoteText{i}.x = 36; quoteText{i}.y = 148;
  quoteText{i}.textAutoResize = 'HEIGHT';
  quoteText{i}.resize(568, 44);
  quoteText{i}.characters = {_js_string(f'"{quote}"')};
  frame{i}.appendChild(quoteText{i});

  // Goal
  const goalLabel{i} = figma.createText();
  goalLabel{i}.fontName = {{ family: 'Inter', style: 'Bold' }};
  goalLabel{i}.fontSize = 13; goalLabel{i}.x = 24; goalLabel{i}.y = 224;
  goalLabel{i}.fills = [{{ type: 'SOLID', color: {{ r: 0.2, g: 0.5, b: 1 }} }}];
  goalLabel{i}.characters = 'PRIMARY GOAL';
  frame{i}.appendChild(goalLabel{i});

  const goalText{i} = figma.createText();
  goalText{i}.fontName = {{ family: 'Inter', style: 'Regular' }};
  goalText{i}.fontSize = 14; goalText{i}.x = 24; goalText{i}.y = 242;
  goalText{i}.textAutoResize = 'HEIGHT';
  goalText{i}.resize(592, 40);
  goalText{i}.characters = {_js_string(goal)};
  frame{i}.appendChild(goalText{i});
""")

        # Frustrations (red stickies)
        frust_y = 310
        lines.append(f"""
  const frustLabel{i} = figma.createText();
  frustLabel{i}.fontName = {{ family: 'Inter', style: 'Bold' }};
  frustLabel{i}.fontSize = 13; frustLabel{i}.x = 24; frustLabel{i}.y = {frust_y};
  frustLabel{i}.fills = [{{ type: 'SOLID', color: {{ r: 0.8, g: 0.1, b: 0.1 }} }}];
  frustLabel{i}.characters = 'FRUSTRATIONS';
  frame{i}.appendChild(frustLabel{i});""")

        for fi, fr in enumerate(frustrations[:3]):
            fy = frust_y + 24 + fi * 56
            lines.append(f"""
  const fr{i}_{fi} = figma.createSticky();
  fr{i}_{fi}.x = {col_x + 24}; fr{i}_{fi}.y = {fy};
  fr{i}_{fi}.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 0.7, b: 0.7 }} }}];
  await figma.loadFontAsync({{ family: 'Inter', style: 'Medium' }});
  fr{i}_{fi}.text.characters = {_js_string(fr)};
  figma.currentPage.appendChild(fr{i}_{fi});""")

        # Motivations (green stickies)
        mot_y = frust_y + 24 + 3 * 56 + 20
        lines.append(f"""
  const motLabel{i} = figma.createText();
  motLabel{i}.fontName = {{ family: 'Inter', style: 'Bold' }};
  motLabel{i}.fontSize = 13; motLabel{i}.x = 24; motLabel{i}.y = {mot_y};
  motLabel{i}.fills = [{{ type: 'SOLID', color: {{ r: 0.1, g: 0.6, b: 0.2 }} }}];
  motLabel{i}.characters = 'MOTIVATIONS';
  frame{i}.appendChild(motLabel{i});""")

        for mi_, mo in enumerate(motivations[:3]):
            my = mot_y + 24 + mi_ * 56
            lines.append(f"""
  const mo{i}_{mi_} = figma.createSticky();
  mo{i}_{mi_}.x = {col_x + 24}; mo{i}_{mi_}.y = {my};
  mo{i}_{mi_}.fills = [{{ type: 'SOLID', color: {{ r: 0.75, g: 1, b: 0.75 }} }}];
  mo{i}_{mi_}.text.characters = {_js_string(mo)};
  figma.currentPage.appendChild(mo{i}_{mi_});""")

    return "\n".join(lines)


def _build_affinity_board(data: dict) -> str:
    clusters = data.get("affinity_clusters", [])
    hmw = data.get("opportunities", [])
    critical = data.get("critical_insights", [])
    lines = []

    cluster_colors = {
        "yellow": "{ r: 1.0, g: 0.95, b: 0.4, a: 1 }",
        "pink":   "{ r: 1.0, g: 0.75, b: 0.85, a: 1 }",
        "blue":   "{ r: 0.7, g: 0.87, b: 1.0, a: 1 }",
        "green":  "{ r: 0.75, g: 1.0, b: 0.75, a: 1 }",
        "orange": "{ r: 1.0, g: 0.85, b: 0.55, a: 1 }",
    }
    default_color = "{ r: 1.0, g: 0.95, b: 0.4, a: 1 }"

    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });")

    for ci, cluster in enumerate(clusters):
        cx = ci * 500
        cluster_name = cluster.get("cluster_name", f"Cluster {ci+1}")
        color_key = cluster.get("theme_colour", "yellow").lower()
        color = cluster_colors.get(color_key, default_color)
        observations = cluster.get("observations", [])
        insight = cluster.get("cluster_insight", "")

        # Cluster header
        lines.append(f"""
  // Cluster {ci+1}: {cluster_name}
  const clusterHdr{ci} = figma.createRectangle();
  clusterHdr{ci}.x = {cx}; clusterHdr{ci}.y = 0;
  clusterHdr{ci}.resize(460, 60);
  clusterHdr{ci}.fills = [{{ type: 'SOLID', color: {{ r: 0.12, g: 0.12, b: 0.12 }} }}];
  clusterHdr{ci}.cornerRadius = 8;
  figma.currentPage.appendChild(clusterHdr{ci});

  const clusterTitle{ci} = figma.createText();
  clusterTitle{ci}.fontName = {{ family: 'Inter', style: 'Bold' }};
  clusterTitle{ci}.fontSize = 18; clusterTitle{ci}.x = {cx + 16}; clusterTitle{ci}.y = 18;
  clusterTitle{ci}.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 1, b: 1 }} }}];
  clusterTitle{ci}.characters = {_js_string(cluster_name)};
  figma.currentPage.appendChild(clusterTitle{ci});""")

        # Stickies for observations
        for oi, obs in enumerate(observations[:5]):
            sy = 80 + oi * 200
            lines.append(f"""
  const obs{ci}_{oi} = figma.createSticky();
  obs{ci}_{oi}.x = {cx + 16}; obs{ci}_{oi}.y = {sy};
  obs{ci}_{oi}.fills = [{{ type: 'SOLID', color: {color} }}];
  obs{ci}_{oi}.text.characters = {_js_string(obs)};
  figma.currentPage.appendChild(obs{ci}_{oi});""")

        # Insight sticky at bottom
        lines.append(f"""
  const insight{ci} = figma.createSticky();
  insight{ci}.x = {cx + 16}; insight{ci}.y = {80 + len(observations[:5]) * 200 + 20};
  insight{ci}.fills = [{{ type: 'SOLID', color: {{ r: 0.85, g: 0.75, b: 1.0, a: 1 }} }}];
  insight{ci}.text.characters = {_js_string("💡 " + insight)};
  figma.currentPage.appendChild(insight{ci});""")

    # HMW section
    hmw_x = len(clusters) * 500 + 60
    lines.append(f"""
  // ─── How Might We Statements ───
  const hmwHdr = figma.createRectangle();
  hmwHdr.x = {hmw_x}; hmwHdr.y = 0;
  hmwHdr.resize(460, 60);
  hmwHdr.fills = [{{ type: 'SOLID', color: {{ r: 0.2, g: 0.4, b: 0.9 }} }}];
  hmwHdr.cornerRadius = 8;
  figma.currentPage.appendChild(hmwHdr);

  const hmwTitle = figma.createText();
  hmwTitle.fontName = {{ family: 'Inter', style: 'Bold' }};
  hmwTitle.fontSize = 18; hmwTitle.x = {hmw_x + 16}; hmwTitle.y = 18;
  hmwTitle.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 1, b: 1 }} }}];
  hmwTitle.characters = 'How Might We...';
  figma.currentPage.appendChild(hmwTitle);""")

    for hi, hmw_item in enumerate(hmw[:7]):
        hy = 80 + hi * 200
        lines.append(f"""
  const hmw{hi} = figma.createSticky();
  hmw{hi}.x = {hmw_x + 16}; hmw{hi}.y = {hy};
  hmw{hi}.fills = [{{ type: 'SOLID', color: {{ r: 0.7, g: 0.87, b: 1.0, a: 1 }} }}];
  hmw{hi}.text.characters = {_js_string(hmw_item)};
  figma.currentPage.appendChild(hmw{hi});""")

    return "\n".join(lines)


def _build_journey_board(data: dict) -> str:
    stages = data.get("journey_stages", [])
    persona = data.get("persona_used", "User")
    lines = []

    STAGE_W = 280
    ROW_H = 180
    START_X = 120
    START_Y = 100

    row_labels = ["STAGE", "TOUCHPOINTS", "USER ACTIONS", "THOUGHTS", "EMOTIONS", "PAIN POINTS", "OPPORTUNITIES"]
    row_colors = [
        "{ r: 0.1, g: 0.1, b: 0.1 }",
        "{ r: 0.2, g: 0.4, b: 0.8 }",
        "{ r: 0.3, g: 0.3, b: 0.3 }",
        "{ r: 0.5, g: 0.3, b: 0.7 }",
        "{ r: 0.1, g: 0.5, b: 0.3 }",
        "{ r: 0.7, g: 0.1, b: 0.1 }",
        "{ r: 0.1, g: 0.5, b: 0.5 }",
    ]

    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });")

    # Title
    lines.append(f"""
  const journeyTitle = figma.createText();
  journeyTitle.fontName = {{ family: 'Inter', style: 'Bold' }};
  journeyTitle.fontSize = 28; journeyTitle.x = {START_X}; journeyTitle.y = 20;
  journeyTitle.characters = {_js_string(f"User Journey Map — {persona}")};
  figma.currentPage.appendChild(journeyTitle);""")

    # Row headers
    for ri, (label, color) in enumerate(zip(row_labels, row_colors)):
        ry = START_Y + ri * ROW_H
        lines.append(f"""
  const rowHdr{ri} = figma.createRectangle();
  rowHdr{ri}.x = 0; rowHdr{ri}.y = {ry};
  rowHdr{ri}.resize(110, {ROW_H - 8});
  rowHdr{ri}.fills = [{{ type: 'SOLID', color: {color} }}];
  figma.currentPage.appendChild(rowHdr{ri});

  const rowLabel{ri} = figma.createText();
  rowLabel{ri}.fontName = {{ family: 'Inter', style: 'Bold' }};
  rowLabel{ri}.fontSize = 10; rowLabel{ri}.x = 8; rowLabel{ri}.y = {ry + (ROW_H - 8) // 2 - 6};
  rowLabel{ri}.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 1, b: 1 }} }}];
  rowLabel{ri}.characters = {_js_string(label)};
  figma.currentPage.appendChild(rowLabel{ri});""")

    # Stage columns
    for si, stage in enumerate(stages):
        sx = START_X + si * STAGE_W
        stage_name = stage.get("stage_name", f"Stage {si+1}")
        emotion_score = stage.get("emotion_score", 0)
        emotion_emoji = "😊" if emotion_score > 0 else "😔" if emotion_score < 0 else "😐"

        # Stage name header
        ry = START_Y
        lines.append(f"""
  const stageHdr{si} = figma.createRectangle();
  stageHdr{si}.x = {sx}; stageHdr{si}.y = {ry};
  stageHdr{si}.resize({STAGE_W - 8}, {ROW_H - 8});
  stageHdr{si}.fills = [{{ type: 'SOLID', color: {{ r: 0.9, g: 0.9, b: 0.9 }} }}];
  stageHdr{si}.cornerRadius = 6;
  figma.currentPage.appendChild(stageHdr{si});

  const stageLabel{si} = figma.createText();
  stageLabel{si}.fontName = {{ family: 'Inter', style: 'Bold' }};
  stageLabel{si}.fontSize = 15; stageLabel{si}.x = {sx + 12}; stageLabel{si}.y = {ry + 20};
  stageLabel{si}.characters = {_js_string(stage_name)};
  figma.currentPage.appendChild(stageLabel{si});""")

        # Touchpoints (row 1)
        touchpoints = "; ".join(stage.get("touchpoints", [])[:2])
        ry1 = START_Y + ROW_H
        lines.append(f"""
  const tp{si} = figma.createSticky();
  tp{si}.x = {sx}; tp{si}.y = {ry1};
  tp{si}.fills = [{{ type: 'SOLID', color: {{ r: 0.85, g: 0.92, b: 1.0, a: 1 }} }}];
  tp{si}.text.characters = {_js_string(touchpoints)};
  figma.currentPage.appendChild(tp{si});""")

        # Actions (row 2)
        actions = "\n".join(f"• {a}" for a in stage.get("user_actions", [])[:3])
        ry2 = START_Y + ROW_H * 2
        lines.append(f"""
  const act{si} = figma.createSticky();
  act{si}.x = {sx}; act{si}.y = {ry2};
  act{si}.fills = [{{ type: 'SOLID', color: {{ r: 0.95, g: 0.95, b: 0.95, a: 1 }} }}];
  act{si}.text.characters = {_js_string(actions)};
  figma.currentPage.appendChild(act{si});""")

        # Thoughts (row 3)
        thoughts = stage.get("thoughts", "")
        ry3 = START_Y + ROW_H * 3
        lines.append(f"""
  const th{si} = figma.createSticky();
  th{si}.x = {sx}; th{si}.y = {ry3};
  th{si}.fills = [{{ type: 'SOLID', color: {{ r: 0.95, g: 0.87, b: 1.0, a: 1 }} }}];
  th{si}.text.characters = {_js_string(f'"{thoughts}"')};
  figma.currentPage.appendChild(th{si});""")

        # Emotions (row 4)
        emotions = " ".join(stage.get("emotions", [])[:2])
        ry4 = START_Y + ROW_H * 4
        lines.append(f"""
  const em{si} = figma.createSticky();
  em{si}.x = {sx}; em{si}.y = {ry4};
  em{si}.fills = [{{ type: 'SOLID', color: {{ r: 0.85, g: 1.0, b: 0.85, a: 1 }} }}];
  em{si}.text.characters = {_js_string(f"{emotion_emoji} {emotions} (score: {emotion_score})")};
  figma.currentPage.appendChild(em{si});""")

        # Pain Points (row 5)
        pains = "\n".join(f"⚠ {pp}" for pp in stage.get("pain_points", [])[:2])
        ry5 = START_Y + ROW_H * 5
        lines.append(f"""
  const pp{si} = figma.createSticky();
  pp{si}.x = {sx}; pp{si}.y = {ry5};
  pp{si}.fills = [{{ type: 'SOLID', color: {{ r: 1.0, g: 0.75, b: 0.75, a: 1 }} }}];
  pp{si}.text.characters = {_js_string(pains)};
  figma.currentPage.appendChild(pp{si});""")

        # Opportunities (row 6)
        opps = "\n".join(f"💡 {op}" for op in stage.get("opportunities", [])[:2])
        ry6 = START_Y + ROW_H * 6
        lines.append(f"""
  const op{si} = figma.createSticky();
  op{si}.x = {sx}; op{si}.y = {ry6};
  op{si}.fills = [{{ type: 'SOLID', color: {{ r: 1.0, g: 0.95, b: 0.7, a: 1 }} }}];
  op{si}.text.characters = {_js_string(opps)};
  figma.currentPage.appendChild(op{si});""")

    return "\n".join(lines)


def _build_design_thinking_board(data: dict) -> str:
    phases = data.get("phases", [])
    lines = []

    phase_colors = {
        "Empathize": "{ r: 1.0, g: 0.75, b: 0.4 }",
        "Define":    "{ r: 0.4, g: 0.75, b: 1.0 }",
        "Ideate":    "{ r: 0.75, g: 1.0, b: 0.4 }",
        "Prototype": "{ r: 1.0, g: 0.4, b: 0.75 }",
        "Test":      "{ r: 0.75, g: 0.4, b: 1.0 }",
    }
    default_phase_color = "{ r: 0.85, g: 0.85, b: 0.85 }"

    PHASE_W = 480
    GAP = 40
    PHASE_H = 700

    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });")

    lines.append(f"""
  const dtTitle = figma.createText();
  dtTitle.fontName = {{ family: 'Inter', style: 'Bold' }};
  dtTitle.fontSize = 32; dtTitle.x = 0; dtTitle.y = 0;
  dtTitle.characters = 'Design Thinking Canvas';
  figma.currentPage.appendChild(dtTitle);""")

    for pi, phase in enumerate(phases[:5]):
        px = pi * (PHASE_W + GAP)
        phase_name = phase.get("phase_name", f"Phase {pi+1}")
        base_color = phase_colors.get(phase_name, default_phase_color)
        questions = phase.get("key_questions", [])
        activities = phase.get("activities", [])
        insights = phase.get("insights", "")
        outputs = phase.get("outputs", [])

        lines.append(f"""
  // Phase: {phase_name}
  const phaseFrame{pi} = figma.createFrame();
  phaseFrame{pi}.x = {px}; phaseFrame{pi}.y = 60;
  phaseFrame{pi}.resize({PHASE_W}, {PHASE_H});
  phaseFrame{pi}.fills = [{{ type: 'SOLID', color: {{ r: 0.98, g: 0.98, b: 0.98 }} }}];
  phaseFrame{pi}.cornerRadius = 12;
  phaseFrame{pi}.name = {_js_string(phase_name)};
  figma.currentPage.appendChild(phaseFrame{pi});

  const phaseHdr{pi} = figma.createRectangle();
  phaseHdr{pi}.resize({PHASE_W}, 80); phaseHdr{pi}.x = 0; phaseHdr{pi}.y = 0;
  phaseHdr{pi}.fills = [{{ type: 'SOLID', color: {base_color} }}];
  phaseFrame{pi}.appendChild(phaseHdr{pi});

  await figma.loadFontAsync({{ family: 'Inter', style: 'Bold' }});
  const phaseTitle{pi} = figma.createText();
  phaseTitle{pi}.fontName = {{ family: 'Inter', style: 'Bold' }};
  phaseTitle{pi}.fontSize = 22; phaseTitle{pi}.x = 24; phaseTitle{pi}.y = 28;
  phaseTitle{pi}.characters = {_js_string(phase_name)};
  phaseFrame{pi}.appendChild(phaseTitle{pi});

  // Key Questions section
  const qLabel{pi} = figma.createText();
  qLabel{pi}.fontName = {{ family: 'Inter', style: 'Bold' }};
  qLabel{pi}.fontSize = 12; qLabel{pi}.x = 24; qLabel{pi}.y = 100;
  qLabel{pi}.fills = [{{ type: 'SOLID', color: {{ r: 0.4, g: 0.4, b: 0.4 }} }}];
  qLabel{pi}.characters = 'KEY QUESTIONS';
  phaseFrame{pi}.appendChild(qLabel{pi});""")

        for qi, q in enumerate(questions[:3]):
            qy = 120 + qi * 60
            lines.append(f"""
  const q{pi}_{qi} = figma.createSticky();
  q{pi}_{qi}.x = {px + 16}; q{pi}_{qi}.y = {60 + qy};
  q{pi}_{qi}.fills = [{{ type: 'SOLID', color: {{ r: 1.0, g: 0.97, b: 0.8, a: 1 }} }}];
  q{pi}_{qi}.text.characters = {_js_string(q)};
  figma.currentPage.appendChild(q{pi}_{qi});""")

        act_start_y = 120 + 3 * 60 + 20
        lines.append(f"""
  // Activities
  const aLabel{pi} = figma.createText();
  aLabel{pi}.fontName = {{ family: 'Inter', style: 'Bold' }};
  aLabel{pi}.fontSize = 12; aLabel{pi}.x = 24; aLabel{pi}.y = {act_start_y};
  aLabel{pi}.fills = [{{ type: 'SOLID', color: {{ r: 0.4, g: 0.4, b: 0.4 }} }}];
  aLabel{pi}.characters = 'ACTIVITIES';
  phaseFrame{pi}.appendChild(aLabel{pi});""")

        for ai, act in enumerate(activities[:3]):
            ay = act_start_y + 20 + ai * 52
            lines.append(f"""
  const a{pi}_{ai} = figma.createSticky();
  a{pi}_{ai}.x = {px + 16}; a{pi}_{ai}.y = {60 + ay};
  a{pi}_{ai}.fills = [{{ type: 'SOLID', color: {{ r: 0.85, g: 0.95, b: 0.85, a: 1 }} }}];
  a{pi}_{ai}.text.characters = {_js_string(act)};
  figma.currentPage.appendChild(a{pi}_{ai});""")

        # Insights
        ins_y = act_start_y + 20 + 3 * 52 + 20
        lines.append(f"""
  const ins{pi} = figma.createText();
  ins{pi}.fontName = {{ family: 'Inter', style: 'Regular' }};
  ins{pi}.fontSize = 13; ins{pi}.x = 24; ins{pi}.y = {ins_y};
  ins{pi}.textAutoResize = 'HEIGHT';
  ins{pi}.resize(432, 80);
  ins{pi}.characters = {_js_string(insights[:200])};
  phaseFrame{pi}.appendChild(ins{pi});""")

    return "\n".join(lines)


def _build_ux_laws_board(data: dict) -> str:
    laws = data.get("laws", [])
    lines = []

    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });")
    lines.append("  await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });")

    lines.append(f"""
  const lawsTitle = figma.createText();
  lawsTitle.fontName = {{ family: 'Inter', style: 'Bold' }};
  lawsTitle.fontSize = 32; lawsTitle.x = 0; lawsTitle.y = 0;
  lawsTitle.characters = 'UX Laws & Principles Reference';
  figma.currentPage.appendChild(lawsTitle);""")

    CARD_W = 440
    CARD_H = 280
    COLS = 3
    GAP_X = 40
    GAP_Y = 40
    START_Y = 80

    priority_colors = {
        "high":   "{ r: 1.0, g: 0.3, b: 0.3 }",
        "medium": "{ r: 1.0, g: 0.7, b: 0.2 }",
        "low":    "{ r: 0.5, g: 0.8, b: 0.5 }",
    }

    for li, law in enumerate(laws):
        col = li % COLS
        row = li // COLS
        lx = col * (CARD_W + GAP_X)
        ly = START_Y + row * (CARD_H + GAP_Y)
        law_name = law.get("law_name", "Law")
        definition = law.get("definition", "")
        application = law.get("application", "")
        implication = law.get("implication", "")
        priority = law.get("priority", "medium").lower()
        p_color = priority_colors.get(priority, priority_colors["medium"])

        lines.append(f"""
  // Law: {law_name}
  const card{li} = figma.createFrame();
  card{li}.x = {lx}; card{li}.y = {ly};
  card{li}.resize({CARD_W}, {CARD_H});
  card{li}.fills = [{{ type: 'SOLID', color: {{ r: 0.97, g: 0.97, b: 0.97 }} }}];
  card{li}.cornerRadius = 8;
  card{li}.name = {_js_string(law_name)};
  figma.currentPage.appendChild(card{li});

  // Priority bar
  const pbar{li} = figma.createRectangle();
  pbar{li}.resize({CARD_W}, 6); pbar{li}.x = 0; pbar{li}.y = 0;
  pbar{li}.fills = [{{ type: 'SOLID', color: {p_color} }}];
  card{li}.appendChild(pbar{li});

  const lTitle{li} = figma.createText();
  lTitle{li}.fontName = {{ family: 'Inter', style: 'Bold' }};
  lTitle{li}.fontSize = 16; lTitle{li}.x = 16; lTitle{li}.y = 18;
  lTitle{li}.characters = {_js_string(law_name)};
  card{li}.appendChild(lTitle{li});

  const lDef{li} = figma.createText();
  lDef{li}.fontName = {{ family: 'Inter', style: 'Regular' }};
  lDef{li}.fontSize = 12; lDef{li}.x = 16; lDef{li}.y = 44;
  lDef{li}.fills = [{{ type: 'SOLID', color: {{ r: 0.4, g: 0.4, b: 0.4 }} }}];
  lDef{li}.textAutoResize = 'HEIGHT';
  lDef{li}.resize({CARD_W - 32}, 36);
  lDef{li}.characters = {_js_string(definition[:120])};
  card{li}.appendChild(lDef{li});

  const lDiv{li} = figma.createRectangle();
  lDiv{li}.resize({CARD_W - 32}, 1); lDiv{li}.x = 16; lDiv{li}.y = 92;
  lDiv{li}.fills = [{{ type: 'SOLID', color: {{ r: 0.85, g: 0.85, b: 0.85 }} }}];
  card{li}.appendChild(lDiv{li});

  const lApp{li} = figma.createText();
  lApp{li}.fontName = {{ family: 'Inter', style: 'Regular' }};
  lApp{li}.fontSize = 12; lApp{li}.x = 16; lApp{li}.y = 100;
  lApp{li}.textAutoResize = 'HEIGHT';
  lApp{li}.resize({CARD_W - 32}, 100);
  lApp{li}.characters = {_js_string(application[:200])};
  card{li}.appendChild(lApp{li});

  const lImpl{li} = figma.createRectangle();
  lImpl{li}.resize({CARD_W - 32}, 44); lImpl{li}.x = 16; lImpl{li}.y = {CARD_H - 60};
  lImpl{li}.fills = [{{ type: 'SOLID', color: {{ r: 0.95, g: 1.0, b: 0.95 }} }}];
  lImpl{li}.cornerRadius = 4;
  card{li}.appendChild(lImpl{li});

  const lImplText{li} = figma.createText();
  lImplText{li}.fontName = {{ family: 'Inter', style: 'Medium' }};
  lImplText{li}.fontSize = 11; lImplText{li}.x = 24; lImplText{li}.y = {CARD_H - 52};
  lImplText{li}.textAutoResize = 'HEIGHT';
  lImplText{li}.resize({CARD_W - 48}, 32);
  lImplText{li}.characters = {_js_string("→ " + implication[:140])};
  card{li}.appendChild(lImplText{li});""")

    return "\n".join(lines)


def _build_generic_board(data: dict) -> str:
    lines = ["  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });"]
    lines.append(f"""
  const t = figma.createText();
  t.fontName = {{ family: 'Inter', style: 'Bold' }};
  t.fontSize = 24; t.x = 0; t.y = 0;
  t.characters = {_js_string(str(data)[:200])};
  figma.currentPage.appendChild(t);""")
    return "\n".join(lines)
