"""
Generates Figma Plugin API JavaScript for creating black-and-white wireframe frames.
Each screen becomes a 375x812 frame with annotated UI regions.
"""
import json
from typing import Any


def _js(s: Any) -> str:
    return json.dumps(str(s))


def build_wireframe_script(wireframes_data: dict, design_system_data: dict) -> str:
    screens = wireframes_data.get("screens", [])
    flow_connections = wireframes_data.get("flow_connections", [])
    body = _build_wireframe_body(screens, flow_connections, design_system_data)
    return _wrap(body)


def _wrap(body: str) -> str:
    return f"""// ===================================================
// Low-Fidelity Wireframes — Black & White
// Generated by UX Research Agent
// Paste into: Figma → Plugins → Development → Open Console
// ===================================================

async function run() {{
  figma.currentPage.name = 'Low-fi Wireframes';

  await figma.loadFontAsync({{ family: 'Inter', style: 'Bold' }});
  await figma.loadFontAsync({{ family: 'Inter', style: 'Regular' }});
  await figma.loadFontAsync({{ family: 'Inter', style: 'Medium' }});

{body}

  figma.viewport.scrollAndZoomIntoView(figma.currentPage.children);
  figma.notify('Wireframes created! ' + figma.currentPage.children.length + ' frames.');
  figma.closePlugin();
}}

run().catch(err => {{
  figma.notify('Error: ' + err.message, {{ error: true }});
  figma.closePlugin();
}});"""


def _build_wireframe_body(screens: list, connections: list, ds: dict) -> str:
    SCREEN_W = 375
    SCREEN_H = 812
    GAP = 80
    lines = []

    lines.append(f"""
  // ─── Wireframe Color Palette ───
  const WF = {{
    bg: {{ r: 1, g: 1, b: 1 }},
    border: {{ r: 0.75, g: 0.75, b: 0.75 }},
    dark: {{ r: 0.12, g: 0.12, b: 0.12 }},
    mid: {{ r: 0.5, g: 0.5, b: 0.5 }},
    light: {{ r: 0.9, g: 0.9, b: 0.9 }},
    accent: {{ r: 0.12, g: 0.12, b: 0.12 }},
    placeholder: {{ r: 0.85, g: 0.85, b: 0.85 }},
    stroke: 1
  }};

  function addStroke(node, color) {{
    node.strokes = [{{ type: 'SOLID', color: color }}];
    node.strokeWeight = 1;
    node.strokeAlign = 'INSIDE';
  }}

  function createLabel(text, x, y, size, bold, parent) {{
    const t = figma.createText();
    t.fontName = {{ family: 'Inter', style: bold ? 'Bold' : 'Regular' }};
    t.fontSize = size; t.x = x; t.y = y;
    t.characters = text;
    t.fills = [{{ type: 'SOLID', color: WF.dark }}];
    parent.appendChild(t);
    return t;
  }}

  function createRect(x, y, w, h, filled, parent, radius) {{
    const r = figma.createRectangle();
    r.x = x; r.y = y; r.resize(w, h);
    r.fills = filled ? [{{ type: 'SOLID', color: WF.placeholder }}] : [{{ type: 'SOLID', color: WF.bg }}];
    addStroke(r, WF.border);
    if (radius) r.cornerRadius = radius;
    parent.appendChild(r);
    return r;
  }}

  function createDivider(x, y, w, parent) {{
    const d = figma.createRectangle();
    d.x = x; d.y = y; d.resize(w, 1);
    d.fills = [{{ type: 'SOLID', color: WF.border }}];
    parent.appendChild(d);
    return d;
  }}

  function createButton(x, y, w, h, label, filled, parent) {{
    const btn = figma.createFrame();
    btn.x = x; btn.y = y; btn.resize(w, h);
    btn.fills = filled ? [{{ type: 'SOLID', color: WF.dark }}] : [{{ type: 'SOLID', color: WF.bg }}];
    btn.cornerRadius = 8;
    addStroke(btn, WF.dark);
    const bt = figma.createText();
    bt.fontName = {{ family: 'Inter', style: 'Medium' }};
    bt.fontSize = 14; bt.x = 8; bt.y = (h - 20) / 2;
    bt.characters = label;
    bt.fills = [{{ type: 'SOLID', color: filled ? WF.bg : WF.dark }}];
    bt.textAlignHorizontal = 'CENTER';
    bt.resize(w - 16, 20);
    btn.appendChild(bt);
    parent.appendChild(btn);
    return btn;
  }}

  function createInputField(x, y, w, placeholder, parent) {{
    const inp = figma.createFrame();
    inp.x = x; inp.y = y; inp.resize(w, 48);
    inp.fills = [{{ type: 'SOLID', color: WF.bg }}];
    inp.cornerRadius = 6;
    addStroke(inp, WF.border);
    const ph = figma.createText();
    ph.fontName = {{ family: 'Inter', style: 'Regular' }};
    ph.fontSize = 14; ph.x = 12; ph.y = 14;
    ph.characters = placeholder;
    ph.fills = [{{ type: 'SOLID', color: WF.mid }}];
    inp.appendChild(ph);
    parent.appendChild(inp);
    return inp;
  }}

  function createImagePlaceholder(x, y, w, h, label, parent) {{
    const img = figma.createFrame();
    img.x = x; img.y = y; img.resize(w, h);
    img.fills = [{{ type: 'SOLID', color: WF.placeholder }}];
    addStroke(img, WF.border);
    // X mark lines (conceptual - use diagonal text)
    const lt = figma.createText();
    lt.fontName = {{ family: 'Inter', style: 'Regular' }};
    lt.fontSize = 11; lt.x = 8; lt.y = h / 2 - 8;
    lt.characters = label || 'Image';
    lt.fills = [{{ type: 'SOLID', color: WF.mid }}];
    img.appendChild(lt);
    parent.appendChild(img);
    return img;
  }}
""")

    for si, screen in enumerate(screens):
        sx = si * (SCREEN_W + GAP)
        screen_name = screen.get("screen_name", f"Screen {si+1}")
        purpose = screen.get("screen_purpose", screen.get("purpose", ""))
        layout_type = screen.get("layout_type", "single-column")
        regions = screen.get("regions", [])
        components = screen.get("components_used", [])
        interactions = screen.get("interactions", [])
        annotations = screen.get("annotations", [])
        description = screen.get("wireframe_description", "")

        lines.append(f"""
  // ───────────────────────────────────────────────────
  // SCREEN {si + 1}: {screen_name}
  // ───────────────────────────────────────────────────
  const screen{si} = figma.createFrame();
  screen{si}.x = {sx}; screen{si}.y = 0;
  screen{si}.resize({SCREEN_W}, {SCREEN_H});
  screen{si}.fills = [{{ type: 'SOLID', color: WF.bg }}];
  screen{si}.name = {_js(screen_name)};
  addStroke(screen{si}, WF.border);
  figma.currentPage.appendChild(screen{si});

  // Screen title label (above frame)
  const screenTitle{si} = figma.createText();
  screenTitle{si}.fontName = {{ family: 'Inter', style: 'Bold' }};
  screenTitle{si}.fontSize = 14; screenTitle{si}.x = {sx}; screenTitle{si}.y = -32;
  screenTitle{si}.characters = {_js(f"{si+1}. {screen_name}")};
  figma.currentPage.appendChild(screenTitle{si});

  // Screen purpose label (above frame)
  const screenPurpose{si} = figma.createText();
  screenPurpose{si}.fontName = {{ family: 'Inter', style: 'Regular' }};
  screenPurpose{si}.fontSize = 11; screenPurpose{si}.x = {sx}; screenPurpose{si}.y = -16;
  screenPurpose{si}.fills = [{{ type: 'SOLID', color: WF.mid }}];
  screenPurpose{si}.characters = {_js(purpose[:80])};
  figma.currentPage.appendChild(screenPurpose{si});
""")

        # Build regions
        current_y = 0
        for ri, region in enumerate(regions):
            region_name = region.get("region_name", f"region_{ri}")
            region_h = region.get("height_px", 60)
            bg_key = region.get("background", "white")
            bg_color = {
                "white":      "WF.bg",
                "light-gray": "WF.light",
                "dark":       "WF.dark",
            }.get(bg_key, "WF.bg")
            contents = region.get("contents", [])

            lines.append(f"""
  // Region: {region_name}
  const region{si}_{ri} = figma.createFrame();
  region{si}_{ri}.x = 0; region{si}_{ri}.y = {current_y};
  region{si}_{ri}.resize({SCREEN_W}, {region_h});
  region{si}_{ri}.fills = [{{ type: 'SOLID', color: {bg_color} }}];
  region{si}_{ri}.name = {_js(region_name)};
  screen{si}.appendChild(region{si}_{ri});""")

            # Render contents
            content_y = 0
            for ci2, content in enumerate(contents[:6]):
                elem = content.get("element", "rectangle")
                label_text = content.get("label", "")
                width_spec = content.get("width", "full")
                height_spec = content.get("height", "40px")
                style = content.get("style", "filled")

                # Parse width
                if width_spec == "full":
                    elem_w = SCREEN_W - 32
                elif width_spec == "half":
                    elem_w = (SCREEN_W - 48) // 2
                elif width_spec == "third":
                    elem_w = (SCREEN_W - 64) // 3
                else:
                    try:
                        elem_w = int(str(width_spec).replace("px", ""))
                    except ValueError:
                        elem_w = SCREEN_W - 32

                # Parse height
                try:
                    elem_h = int(str(height_spec).replace("px", "").replace("auto", "40"))
                except (ValueError, AttributeError):
                    elem_h = 40

                elem_h = max(elem_h, 24)

                if elem in ("text", "label", "heading") or "text" in elem:
                    size = 20 if "heading" in elem else 14
                    bold = "heading" in elem or "title" in elem
                    lines.append(f"""
  const ce{si}_{ri}_{ci2} = figma.createText();
  ce{si}_{ri}_{ci2}.fontName = {{ family: 'Inter', style: '{("Bold" if bold else "Regular")}' }};
  ce{si}_{ri}_{ci2}.fontSize = {size}; ce{si}_{ri}_{ci2}.x = 16; ce{si}_{ri}_{ci2}.y = {content_y + 8};
  ce{si}_{ri}_{ci2}.characters = {_js(label_text[:80])};
  ce{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: {'WF.bg' if bg_key == 'dark' else 'WF.dark'} }}];
  region{si}_{ri}.appendChild(ce{si}_{ri}_{ci2});""")

                elif "button" in elem or style in ("filled", "outlined"):
                    is_filled = style == "filled"
                    lines.append(f"""
  const btn{si}_{ri}_{ci2} = figma.createFrame();
  btn{si}_{ri}_{ci2}.x = 16; btn{si}_{ri}_{ci2}.y = {content_y + 8};
  btn{si}_{ri}_{ci2}.resize({elem_w}, {elem_h});
  btn{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: {('WF.dark' if is_filled else 'WF.bg')} }}];
  btn{si}_{ri}_{ci2}.cornerRadius = 8;
  addStroke(btn{si}_{ri}_{ci2}, WF.dark);
  const btnT{si}_{ri}_{ci2} = figma.createText();
  btnT{si}_{ri}_{ci2}.fontName = {{ family: 'Inter', style: 'Medium' }};
  btnT{si}_{ri}_{ci2}.fontSize = 14; btnT{si}_{ri}_{ci2}.x = 8; btnT{si}_{ri}_{ci2}.y = ({elem_h} - 20) / 2;
  btnT{si}_{ri}_{ci2}.characters = {_js(label_text[:40])};
  btnT{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: {('WF.bg' if is_filled else 'WF.dark')} }}];
  btnT{si}_{ri}_{ci2}.resize({elem_w - 16}, 20);
  btn{si}_{ri}_{ci2}.appendChild(btnT{si}_{ri}_{ci2});
  region{si}_{ri}.appendChild(btn{si}_{ri}_{ci2});""")

                elif "input" in elem or "field" in elem:
                    lines.append(f"""
  const inp{si}_{ri}_{ci2} = figma.createFrame();
  inp{si}_{ri}_{ci2}.x = 16; inp{si}_{ri}_{ci2}.y = {content_y + 8};
  inp{si}_{ri}_{ci2}.resize({elem_w}, 48);
  inp{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.bg }}];
  inp{si}_{ri}_{ci2}.cornerRadius = 6;
  addStroke(inp{si}_{ri}_{ci2}, WF.border);
  const inpT{si}_{ri}_{ci2} = figma.createText();
  inpT{si}_{ri}_{ci2}.fontName = {{ family: 'Inter', style: 'Regular' }};
  inpT{si}_{ri}_{ci2}.fontSize = 14; inpT{si}_{ri}_{ci2}.x = 12; inpT{si}_{ri}_{ci2}.y = 14;
  inpT{si}_{ri}_{ci2}.characters = {_js(label_text[:40])};
  inpT{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.mid }}];
  inp{si}_{ri}_{ci2}.appendChild(inpT{si}_{ri}_{ci2});
  region{si}_{ri}.appendChild(inp{si}_{ri}_{ci2});""")

                elif "image" in elem or "avatar" in elem or "photo" in elem:
                    lines.append(f"""
  const img{si}_{ri}_{ci2} = figma.createRectangle();
  img{si}_{ri}_{ci2}.x = 16; img{si}_{ri}_{ci2}.y = {content_y + 8};
  img{si}_{ri}_{ci2}.resize({elem_w}, {elem_h});
  img{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.placeholder }}];
  addStroke(img{si}_{ri}_{ci2}, WF.border);
  region{si}_{ri}.appendChild(img{si}_{ri}_{ci2});
  const imgL{si}_{ri}_{ci2} = figma.createText();
  imgL{si}_{ri}_{ci2}.fontName = {{ family: 'Inter', style: 'Regular' }};
  imgL{si}_{ri}_{ci2}.fontSize = 11; imgL{si}_{ri}_{ci2}.x = 24; imgL{si}_{ri}_{ci2}.y = {content_y + 8 + elem_h // 2 - 8};
  imgL{si}_{ri}_{ci2}.characters = {_js(label_text or "Image")};
  imgL{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.mid }}];
  region{si}_{ri}.appendChild(imgL{si}_{ri}_{ci2});""")

                elif "divider" in elem or "separator" in elem:
                    lines.append(f"""
  const div{si}_{ri}_{ci2} = figma.createRectangle();
  div{si}_{ri}_{ci2}.x = 0; div{si}_{ri}_{ci2}.y = {content_y + 8};
  div{si}_{ri}_{ci2}.resize({SCREEN_W}, 1);
  div{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.border }}];
  region{si}_{ri}.appendChild(div{si}_{ri}_{ci2});""")

                elif "icon" in elem or "tab" in elem:
                    lines.append(f"""
  const icon{si}_{ri}_{ci2} = figma.createEllipse();
  icon{si}_{ri}_{ci2}.x = 16 + {ci2 * 60}; icon{si}_{ri}_{ci2}.y = {content_y + 8};
  icon{si}_{ri}_{ci2}.resize(24, 24);
  icon{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.placeholder }}];
  region{si}_{ri}.appendChild(icon{si}_{ri}_{ci2});""")

                else:
                    # Generic rectangle placeholder
                    lines.append(f"""
  const el{si}_{ri}_{ci2} = figma.createRectangle();
  el{si}_{ri}_{ci2}.x = 16; el{si}_{ri}_{ci2}.y = {content_y + 8};
  el{si}_{ri}_{ci2}.resize({elem_w}, {elem_h});
  el{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.placeholder }}];
  addStroke(el{si}_{ri}_{ci2}, WF.border);
  region{si}_{ri}.appendChild(el{si}_{ri}_{ci2});
  const elT{si}_{ri}_{ci2} = figma.createText();
  elT{si}_{ri}_{ci2}.fontName = {{ family: 'Inter', style: 'Regular' }};
  elT{si}_{ri}_{ci2}.fontSize = 11; elT{si}_{ri}_{ci2}.x = 24; elT{si}_{ri}_{ci2}.y = {content_y + 8 + max(0, elem_h // 2 - 8)};
  elT{si}_{ri}_{ci2}.characters = {_js(label_text[:40])};
  elT{si}_{ri}_{ci2}.fills = [{{ type: 'SOLID', color: WF.mid }}];
  region{si}_{ri}.appendChild(elT{si}_{ri}_{ci2});""")

                content_y += elem_h + 12

            # Divider between regions
            lines.append(f"""
  createDivider(0, {region_h - 1}, {SCREEN_W}, screen{si});""")

            current_y += region_h

        # Annotations panel (below the frame)
        if annotations:
            ann_text = "\n".join(f"↑ {a}" for a in annotations[:4])
            lines.append(f"""
  // Annotations
  const ann{si} = figma.createText();
  ann{si}.fontName = {{ family: 'Inter', style: 'Regular' }};
  ann{si}.fontSize = 10; ann{si}.x = {sx}; ann{si}.y = {SCREEN_H + 16};
  ann{si}.fills = [{{ type: 'SOLID', color: WF.mid }}];
  ann{si}.textAutoResize = 'HEIGHT';
  ann{si}.resize({SCREEN_W}, 60);
  ann{si}.characters = {_js(ann_text)};
  figma.currentPage.appendChild(ann{si});""")

    # Flow connectors between screens
    for fc in connections:
        from_name = fc.get("from_screen", "")
        to_name = fc.get("to_screen", "")
        trigger = fc.get("trigger", "")

        # Find indices
        from_idx = next((i for i, s in enumerate(screens) if s.get("screen_name") == from_name), -1)
        to_idx = next((i for i, s in enumerate(screens) if s.get("screen_name") == to_name), -1)

        if from_idx >= 0 and to_idx >= 0 and abs(from_idx - to_idx) == 1:
            from_x = from_idx * (SCREEN_W + GAP) + SCREEN_W
            to_x = to_idx * (SCREEN_W + GAP)
            mid_y = SCREEN_H // 2
            lines.append(f"""
  // Flow: {from_name} → {to_name}
  const arrow{from_idx}_{to_idx} = figma.createConnector();
  arrow{from_idx}_{to_idx}.connectorStart = {{ position: {{ x: {from_x}, y: {mid_y} }} }};
  arrow{from_idx}_{to_idx}.connectorEnd = {{ position: {{ x: {to_x}, y: {mid_y} }} }};
  arrow{from_idx}_{to_idx}.strokeWeight = 2;
  arrow{from_idx}_{to_idx}.strokes = [{{ type: 'SOLID', color: WF.dark }}];
  figma.currentPage.appendChild(arrow{from_idx}_{to_idx});

  const arrowLabel{from_idx}_{to_idx} = figma.createText();
  arrowLabel{from_idx}_{to_idx}.fontName = {{ family: 'Inter', style: 'Regular' }};
  arrowLabel{from_idx}_{to_idx}.fontSize = 10;
  arrowLabel{from_idx}_{to_idx}.x = {from_x + 4}; arrowLabel{from_idx}_{to_idx}.y = {mid_y - 14};
  arrowLabel{from_idx}_{to_idx}.characters = {_js(trigger[:30])};
  arrowLabel{from_idx}_{to_idx}.fills = [{{ type: 'SOLID', color: WF.mid }}];
  figma.currentPage.appendChild(arrowLabel{from_idx}_{to_idx});""")

    return "\n".join(lines)


def build_component_sheet_script(design_system_data: dict) -> str:
    """Generates a Figma plugin script to create a component reference sheet."""
    categories = design_system_data.get("component_categories", [])
    tokens = design_system_data.get("design_tokens", {})
    type_scale = tokens.get("type_scale", [])
    color_roles = tokens.get("color_roles", [])
    spacing = tokens.get("spacing", {})

    body = _build_component_sheet_body(categories, type_scale, color_roles, spacing)

    return f"""// ===================================================
// Design System Component Reference Sheet
// Generated by UX Research Agent
// Paste into: Figma → Plugins → Development → Open Console
// ===================================================

async function run() {{
  figma.currentPage.name = 'Design System — Component Reference';

  await figma.loadFontAsync({{ family: 'Inter', style: 'Bold' }});
  await figma.loadFontAsync({{ family: 'Inter', style: 'Regular' }});
  await figma.loadFontAsync({{ family: 'Inter', style: 'Medium' }});

{body}

  figma.viewport.scrollAndZoomIntoView(figma.currentPage.children);
  figma.notify('Component reference sheet created!');
  figma.closePlugin();
}}

run().catch(err => {{
  figma.notify('Error: ' + err.message, {{ error: true }});
  figma.closePlugin();
}});"""


def _build_component_sheet_body(categories: list, type_scale: list, color_roles: list, spacing: dict) -> str:
    lines = []
    CARD_W = 280
    GAP = 32
    CARD_H_BASE = 140

    # Title
    lines.append(f"""
  const sheetTitle = figma.createText();
  sheetTitle.fontName = {{ family: 'Inter', style: 'Bold' }};
  sheetTitle.fontSize = 28; sheetTitle.x = 0; sheetTitle.y = 0;
  sheetTitle.characters = 'Design System — Component Reference';
  figma.currentPage.appendChild(sheetTitle);""")

    col_x = 0
    global_y = 80

    # Design Tokens section
    lines.append(f"""
  // ─── Design Tokens ───
  const tokenHdr = figma.createRectangle();
  tokenHdr.x = 0; tokenHdr.y = {global_y};
  tokenHdr.resize(900, 48);
  tokenHdr.fills = [{{ type: 'SOLID', color: {{ r: 0.12, g: 0.12, b: 0.12 }} }}];
  figma.currentPage.appendChild(tokenHdr);
  const tokenHdrT = figma.createText();
  tokenHdrT.fontName = {{ family: 'Inter', style: 'Bold' }};
  tokenHdrT.fontSize = 16; tokenHdrT.x = 16; tokenHdrT.y = {global_y + 14};
  tokenHdrT.fills = [{{ type: 'SOLID', color: {{ r: 1, g: 1, b: 1 }} }}];
  tokenHdrT.characters = 'DESIGN TOKENS';
  figma.currentPage.appendChild(tokenHdrT);""")

    global_y += 60

    # Color roles
    for ci, role in enumerate(color_roles[:8]):
        cx = ci * 108
        lines.append(f"""
  const cr{ci} = figma.createRectangle();
  cr{ci}.x = {cx}; cr{ci}.y = {global_y};
  cr{ci}.resize(100, 60);
  cr{ci}.fills = [{{ type: 'SOLID', color: {{ r: 0.85, g: 0.85, b: 0.85 }} }}];
  figma.currentPage.appendChild(cr{ci});
  const crT{ci} = figma.createText();
  crT{ci}.fontName = {{ family: 'Inter', style: 'Regular' }};
  crT{ci}.fontSize = 10; crT{ci}.x = {cx + 4}; crT{ci}.y = {global_y + 68};
  crT{ci}.characters = {_js(role)};
  figma.currentPage.appendChild(crT{ci});""")

    global_y += 120

    # Type scale
    lines.append(f"""
  const typeHdrT = figma.createText();
  typeHdrT.fontName = {{ family: 'Inter', style: 'Bold' }};
  typeHdrT.fontSize = 13; typeHdrT.x = 0; typeHdrT.y = {global_y};
  typeHdrT.fills = [{{ type: 'SOLID', color: {{ r: 0.4, g: 0.4, b: 0.4 }} }}];
  typeHdrT.characters = 'TYPE SCALE';
  figma.currentPage.appendChild(typeHdrT);""")

    global_y += 24

    for ti, ts in enumerate(type_scale):
        name = ts.get("name", "")
        size = ts.get("size", "14px")
        weight = ts.get("weight", "400")
        usage = ts.get("usage", "")
        font_size = int(str(size).replace("px", "") or 14)
        style = "Bold" if int(weight) >= 600 else "Regular"

        lines.append(f"""
  const ts{ti} = figma.createText();
  ts{ti}.fontName = {{ family: 'Inter', style: '{style}' }};
  ts{ti}.fontSize = {min(font_size, 32)}; ts{ti}.x = 0; ts{ti}.y = {global_y};
  ts{ti}.characters = {_js(f"{name} — {size}/{weight} — {usage}")};
  figma.currentPage.appendChild(ts{ti});""")
        global_y += font_size + 12

    global_y += 40

    # Component categories
    for cat_idx, cat in enumerate(categories):
        cat_name = cat.get("name", "Category")
        components = cat.get("components", [])

        lines.append(f"""
  // Category: {cat_name}
  const catHdr{cat_idx} = figma.createRectangle();
  catHdr{cat_idx}.x = 0; catHdr{cat_idx}.y = {global_y};
  catHdr{cat_idx}.resize(900, 40);
  catHdr{cat_idx}.fills = [{{ type: 'SOLID', color: {{ r: 0.92, g: 0.92, b: 0.92 }} }}];
  figma.currentPage.appendChild(catHdr{cat_idx});
  const catLabel{cat_idx} = figma.createText();
  catLabel{cat_idx}.fontName = {{ family: 'Inter', style: 'Bold' }};
  catLabel{cat_idx}.fontSize = 14; catLabel{cat_idx}.x = 16; catLabel{cat_idx}.y = {global_y + 12};
  catLabel{cat_idx}.characters = {_js(cat_name.upper())};
  figma.currentPage.appendChild(catLabel{cat_idx});""")

        global_y += 56

        for comp_idx, comp in enumerate(components):
            cx = (comp_idx % 3) * (CARD_W + GAP)
            cy = global_y + (comp_idx // 3) * (CARD_H_BASE + GAP)
            comp_name = comp.get("component_name", "Component")
            variants = comp.get("variants", [])
            priority = comp.get("priority", "must-have")
            states = comp.get("states", [])
            usage = ", ".join(comp.get("usage_context", [])[:2])
            principles = ", ".join(comp.get("ux_principles_applied", [])[:2])

            p_color = {
                "must-have":    "{ r: 0.2, g: 0.7, b: 0.3 }",
                "should-have":  "{ r: 0.9, g: 0.6, b: 0.1 }",
                "nice-to-have": "{ r: 0.6, g: 0.6, b: 0.6 }",
            }.get(priority, "{ r: 0.6, g: 0.6, b: 0.6 }")

            lines.append(f"""
  const comp{cat_idx}_{comp_idx} = figma.createFrame();
  comp{cat_idx}_{comp_idx}.x = {cx}; comp{cat_idx}_{comp_idx}.y = {cy};
  comp{cat_idx}_{comp_idx}.resize({CARD_W}, {CARD_H_BASE});
  comp{cat_idx}_{comp_idx}.fills = [{{ type: 'SOLID', color: {{ r: 0.97, g: 0.97, b: 0.97 }} }}];
  comp{cat_idx}_{comp_idx}.cornerRadius = 8;
  comp{cat_idx}_{comp_idx}.strokes = [{{ type: 'SOLID', color: {{ r: 0.85, g: 0.85, b: 0.85 }} }}];
  comp{cat_idx}_{comp_idx}.strokeWeight = 1;
  comp{cat_idx}_{comp_idx}.name = {_js(comp_name)};
  figma.currentPage.appendChild(comp{cat_idx}_{comp_idx});

  const compPbar{cat_idx}_{comp_idx} = figma.createRectangle();
  compPbar{cat_idx}_{comp_idx}.resize({CARD_W}, 4); compPbar{cat_idx}_{comp_idx}.x = 0; compPbar{cat_idx}_{comp_idx}.y = 0;
  compPbar{cat_idx}_{comp_idx}.fills = [{{ type: 'SOLID', color: {p_color} }}];
  comp{cat_idx}_{comp_idx}.appendChild(compPbar{cat_idx}_{comp_idx});

  const compName{cat_idx}_{comp_idx} = figma.createText();
  compName{cat_idx}_{comp_idx}.fontName = {{ family: 'Inter', style: 'Bold' }};
  compName{cat_idx}_{comp_idx}.fontSize = 14; compName{cat_idx}_{comp_idx}.x = 12; compName{cat_idx}_{comp_idx}.y = 14;
  compName{cat_idx}_{comp_idx}.characters = {_js(comp_name)};
  comp{cat_idx}_{comp_idx}.appendChild(compName{cat_idx}_{comp_idx});

  const compPriority{cat_idx}_{comp_idx} = figma.createText();
  compPriority{cat_idx}_{comp_idx}.fontName = {{ family: 'Inter', style: 'Regular' }};
  compPriority{cat_idx}_{comp_idx}.fontSize = 10; compPriority{cat_idx}_{comp_idx}.x = 12; compPriority{cat_idx}_{comp_idx}.y = 34;
  compPriority{cat_idx}_{comp_idx}.fills = [{{ type: 'SOLID', color: {{ r: 0.5, g: 0.5, b: 0.5 }} }}];
  compPriority{cat_idx}_{comp_idx}.characters = {_js(priority + " · " + ", ".join(variants[:3]))};
  comp{cat_idx}_{comp_idx}.appendChild(compPriority{cat_idx}_{comp_idx});

  const compUsage{cat_idx}_{comp_idx} = figma.createText();
  compUsage{cat_idx}_{comp_idx}.fontName = {{ family: 'Inter', style: 'Regular' }};
  compUsage{cat_idx}_{comp_idx}.fontSize = 11; compUsage{cat_idx}_{comp_idx}.x = 12; compUsage{cat_idx}_{comp_idx}.y = 60;
  compUsage{cat_idx}_{comp_idx}.textAutoResize = 'HEIGHT';
  compUsage{cat_idx}_{comp_idx}.resize({CARD_W - 24}, 36);
  compUsage{cat_idx}_{comp_idx}.characters = {_js("Used in: " + usage)};
  comp{cat_idx}_{comp_idx}.appendChild(compUsage{cat_idx}_{comp_idx});

  const compPrinciples{cat_idx}_{comp_idx} = figma.createText();
  compPrinciples{cat_idx}_{comp_idx}.fontName = {{ family: 'Inter', style: 'Regular' }};
  compPrinciples{cat_idx}_{comp_idx}.fontSize = 10; compPrinciples{cat_idx}_{comp_idx}.x = 12; compPrinciples{cat_idx}_{comp_idx}.y = 104;
  compPrinciples{cat_idx}_{comp_idx}.fills = [{{ type: 'SOLID', color: {{ r: 0.4, g: 0.4, b: 0.7 }} }}];
  compPrinciples{cat_idx}_{comp_idx}.resize({CARD_W - 24}, 24);
  compPrinciples{cat_idx}_{comp_idx}.characters = {_js("Principles: " + principles)};
  comp{cat_idx}_{comp_idx}.appendChild(compPrinciples{cat_idx}_{comp_idx});""")

        rows_used = (len(components) + 2) // 3
        global_y += rows_used * (CARD_H_BASE + GAP) + 24

    return "\n".join(lines)
